libnma: add opengl to REQUIRED_DISTRO_FEATURES
Issue: LINUXEXEC-23251

libnma depends on gtk4 which needs opengl DISTRO_FEATURES enabled.

Fixes:
  ERROR: Nothing PROVIDES 'gtk4' (but /build/layers/meta-openembedded/meta-gnome/recipes-connectivity/libnma/libnma_1.8.38.bb DEPENDS on or otherwise requires it)
  gtk4 was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'network-manager-applet', 'libnma', 'gtk4']

(LOCAL REV: NOT UPSTREAM) -- Sent to meta-oe on 20221117

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>