gnome-calendar: add opengl to REQUIRED_DISTRO_FEATURES
Issue: LINUXEXEC-23251

Fixes:
  ERROR: Nothing PROVIDES 'libadwaita' (but /build/layers/meta-openembedded/meta-gnome/recipes-gnome/gnome-calendar/gnome-calendar_42.0.bb DEPENDS on or otherwise requires it)
  libadwaita was skipped: missing required distro feature 'opengl' (not in DISTRO_FEATURES)
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'gnome-calendar', 'libadwaita']

(LOCAL REV: NOT UPSTREAM) -- Sent to meta-oe on 20221117

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>